package com.example.mdbspringboot.model;

import java.time.LocalDateTime;
import java.util.List;

import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.index.Indexed;
import org.springframework.data.mongodb.core.mapping.Document;
import org.springframework.format.annotation.DateTimeFormat;

import lombok.Data;

@Data // for getters, setters, constructors...
@Document(value = "employees") // so that it can be stored as mongo document
public class Employee {
    @Id // will be autogenerated
    private String id;
    private String firstName;
    private String lastName;
    // @Indexed(unique = true) => will ensure that email is unique
    // to enable index, in application.properties we put:
    // spring.data.mongodb.auto-index-creation=true
    @Indexed(unique = true) 
    private String email;
    private String gender;
    private String department;
    private List<String> projects;
    private Double salary;
    @DateTimeFormat(pattern = "dd-MM-yyyy")
    private LocalDateTime createdAt = LocalDateTime.now();

    public Employee(String firstName, String lastName, String email, String gender, String department, 
            List<String> projects, Double salary) {
        this.firstName = firstName;
        this.lastName = lastName;
        this.email = email;
        this.gender = gender;
        this.department = department;
        this.projects = projects;
        this.salary = salary;
    }
}