version: '3.1'
services:
  database:
    restart: always
    image: postgres:latest
    container_name: postgres-latest
    ports:
      - "54032:5432"
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5