version: "3.8"
services:
# container 1 - mongodb
  mongodb:
    image: mongo # would get the latest version for mongodb
    container_name: mongodb
    ports: 
        - 27017:27017 # host:container
    volumes: 
        - data:/data
    environment: 
        - MONGO_INITDB_ROOT_USERNAME=rootuser
        - MONGO_INITDB_ROOT_PASSWORD=rootpass
# container 2 - mongo-express GUI
  mongo-express:
    image: mongo-express
    container_name: mongo-express
    depends_on:
      - mongodb
    restart: always
    # port 8081 is exposed to allow access to the web interface
    ports: 
        - 8081:8081 # host:container
    environment: 
        - ME_CONFIG_MONGODB_SERVER=mongodb
        - ME_CONFIG_MONGODB_ADMINUSERNAME=rootuser
        - ME_CONFIG_MONGODB_ADMINPASSWORD=rootpass
        - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
        - ME_CONFIG_BASICAUTH_USERNAME=admin #
        - ME_CONFIG_BASICAUTH_PASSWORD=admin123 #
# for storing the data
volumes: 
    data: {}
# for communication between containers
networks:
    default:
        # overriding default name
        name: mongodb_network