###
GET http://localhost:8102/mdb-spring-boot/api/v1/employees/


###
GET http://localhost:8102/mdb-spring-boot/api/v1/employees/123


### valid data
POST http://localhost:8102/mdb-spring-boot/api/v1/employees/create
Content-Type: application/json

{
  "firstName": "Tom",
  "lastName": "Gibson",
  "email": "tom@gibson.com",
  "gender": "Male",
  "department": "R&D",
  "projects": [
    "Project 2",
    "Project 10"
  ],
  "salary": 5600,
  "mobile": "123 345 6789"
}

### invalid data
POST http://localhost:8102/mdb-spring-boot/api/v1/employees/create
Content-Type: application/json

{
  "firstName": "",
  "lastName": null,
  "email": "tomgibson.com",
  "gender": "Male",
  "projects": [],
  "salary": 15600,
  "mobile": "123*345/6789"
}


###
POST http://localhost:8102/mdb-spring-boot/api/v1/employees/create-multiple
Content-Type: application/json

[
  {
    "firstName": "Jane",
    "lastName": "Doe",
    "email": "jane@doe.com",
    "gender": "FEMALE",
    "department": "IT",
    "projects": [
      "Project 2",
      "Project 4",
      "Project 7"
    ],
    "salary": 3500
  },
  {
    "firstName": "Alex",
    "lastName": "Brown",
    "email": "alex@brown.com",
    "gender": "Male",
    "department": "HR",
    "projects": [
      "Project 1",
      "Project 9"
    ],
    "salary": 4200
  }
]


### not working as expected
###
PATCH http://localhost:8102/mdb-spring-boot/api/v1/employees/
Content-Type: application/json

{
  "id": "625c6a85c131622dc1789587",
  "department": "IT",
  "projects": [
    "Project 2",
    "Project 10"
  ]
}


###
PUT http://localhost:8102/mdb-spring-boot/api/v1/employees/ HTTP/1.1
content-type: application/json

{
  "id": "62646a31b80003b970408ea7",
  "firstName": "Rory",
  "lastName": "McGinty",
  "email": "rmcginty1@baidu.com",
  "gender": "Female",
  "department": "R&D",
  "projects": [
    "Project 2",
    "Project 4",
    "Project 5",
    "Project 10"
  ],
  "salary": 4900.0,
  "createdAt": "2016-11-09T22:10:20"
}


###
DELETE http://localhost:8102/mdb-spring-boot/api/v1/employees/delete/?id=62646a31b80003b970408eaa HTTP/1.1


###
DELETE http://localhost:8102/mdb-spring-boot/api/v1/employees/delete-v2/62646a31b80003b970408eab HTTP/1.1


###
DELETE http://localhost:8102/mdb-spring-boot/api/v1/employees/delete-v3?id=62646a31b80003b970408eac HTTP/1.1

###
GET http://localhost:8102/mdb-spring-boot/api/v1/employees/employee-by-email?email=john@smith.com


###
GET http://localhost:8102/mdb-spring-boot/api/v1/employees/page?pagesize=20&fields=firstName,lastName,salary&sortby=firstName&pageno=0 HTTP/1.1


###
GET http://localhost:8102/mdb-spring-boot/api/v1/employees/projects?projects=Project 9,Project 10 HTTP/1.1

## not working
### 
GET http://localhost:8102/mdb-spring-boot/api/v1/employees/example HTTP/1.1
content-type: application/json

{

}

### 
GET http://localhost:8102/mdb-spring-boot/api/v1/employees/first-name?firstName=Al HTTP/1.1


### 
GET http://localhost:8102/mdb-spring-boot/api/v1/employees/department?department=IT HTTP/1.1

### 
GET http://localhost:8102/mdb-spring-boot/api/v1/employees/salary?salary=4000 HTTP/1.1

###
PATCH http://localhost:8102/mdb-spring-boot/api/v1/employees/625c6a85c131622dc1789587
Content-Type: application/json

{
  "id": "625c6a85c131622dc1789587",
  "department": "IT",
  "projects": [
    "Project 2",
    "Project 10"
  ]
}







